// 10 country-themed levels. Each entry drives the character SVG, food projectile,
// background, and level-up cry. Loops back to level 1 with a +prestige badge if
// the player clears all 10.

export const LEVELS = [
  {
    id: 'usa',
    flag: '🇺🇸',
    name: 'Big Billy',
    country: 'USA',
    food: '🍔',
    cry: 'YEEHAW!',
    sky: ['#fb923c', '#f59e0b', '#facc15'],
    ground: '#7c2d12',
    accent: '#ef4444',
    palette: { skin: '#FDBCB4', shirt: '#1d4ed8', pants: '#1e3a5f', hair: '#facc15' },
    accessories: ['cowboyHat'],
  },
  {
    id: 'japan',
    flag: '🇯🇵',
    name: 'Takeshi-san',
    country: 'Japan',
    food: '🍣',
    cry: 'ITADAKIMASU!!',
    sky: ['#fda4af', '#fbcfe8', '#e0f2fe'],
    ground: '#7f1d1d',
    accent: '#e11d48',
    palette: { skin: '#F3D5A0', shirt: '#FFFFFF', pants: '#0f172a', hair: '#0a0a0a' },
    accessories: ['topknot', 'fundoshi'],
  },
  {
    id: 'mexico',
    flag: '🇲🇽',
    name: 'El Gordo',
    country: 'Mexico',
    food: '🌮',
    cry: '¡AY CARAMBA!',
    sky: ['#f59e0b', '#fb923c', '#dc2626'],
    ground: '#78350f',
    accent: '#16a34a',
    palette: { skin: '#C28865', shirt: '#16a34a', pants: '#7c2d12', hair: '#1a0a00' },
    accessories: ['sombrero', 'mustache'],
  },
  {
    id: 'italy',
    flag: '🇮🇹',
    name: 'Mamma Mia Mario',
    country: 'Italy',
    food: '🍕',
    cry: 'MAMMA MIA!',
    sky: ['#22d3ee', '#0ea5e9', '#1e40af'],
    ground: '#365314',
    accent: '#16a34a',
    palette: { skin: '#F1C29A', shirt: '#FFFFFF', pants: '#000000', hair: '#1a0a00' },
    accessories: ['chefHat', 'curlyMustache'],
  },
  {
    id: 'russia',
    flag: '🇷🇺',
    name: 'Boris the Bear',
    country: 'Russia',
    food: '🥟',
    cry: 'DAVAI DAVAI!!',
    sky: ['#cbd5e1', '#94a3b8', '#475569'],
    ground: '#1e293b',
    accent: '#dc2626',
    palette: { skin: '#F4D2B5', shirt: '#7c1d1d', pants: '#1f2937', hair: '#cbd5e1' },
    accessories: ['ushanka', 'beard'],
  },
  {
    id: 'france',
    flag: '🇫🇷',
    name: 'François le Gros',
    country: 'France',
    food: '🥐',
    cry: 'MON DIEU!',
    sky: ['#7c3aed', '#6366f1', '#1e1b4b'],
    ground: '#0f172a',
    accent: '#fbbf24',
    palette: { skin: '#F1C29A', shirt: '#FFFFFF', stripe: '#1d4ed8', pants: '#1e3a5f', hair: '#1a0a00' },
    accessories: ['beret', 'pencilMustache', 'stripes'],
  },
  {
    id: 'india',
    flag: '🇮🇳',
    name: 'Raju Maharaja',
    country: 'India',
    food: '🍛',
    cry: 'BAHUT ACHHA!!',
    sky: ['#f59e0b', '#dc2626', '#7c2d12'],
    ground: '#451a03',
    accent: '#fbbf24',
    palette: { skin: '#A0623F', shirt: '#fbbf24', pants: '#FFFFFF', hair: '#0a0a0a' },
    accessories: ['turban'],
  },
  {
    id: 'brazil',
    flag: '🇧🇷',
    name: 'Carnaval Carlos',
    country: 'Brazil',
    food: '🥩',
    cry: 'ISSO AÍ!!',
    sky: ['#facc15', '#22c55e', '#0ea5e9'],
    ground: '#14532d',
    accent: '#facc15',
    palette: { skin: '#A0623F', shirt: '#22c55e', pants: '#facc15', hair: '#1a0a00' },
    accessories: ['feathers'],
  },
  {
    id: 'germany',
    flag: '🇩🇪',
    name: 'Hans Bratwurst',
    country: 'Germany',
    food: '🥨',
    cry: 'WUNDERBAR!!',
    sky: ['#fde68a', '#f59e0b', '#1e3a8a'],
    ground: '#365314',
    accent: '#dc2626',
    palette: { skin: '#FDBCB4', shirt: '#FFFFFF', pants: '#7c2d12', hair: '#facc15' },
    accessories: ['bavarianHat', 'beard', 'lederhosen'],
  },
  {
    id: 'china',
    flag: '🇨🇳',
    name: 'Wong Da Pang',
    country: 'China',
    food: '🥟',
    cry: 'AIYAH!!',
    sky: ['#dc2626', '#facc15', '#7c1d1d'],
    ground: '#450a0a',
    accent: '#fbbf24',
    palette: { skin: '#F3D5A0', shirt: '#dc2626', pants: '#0a0a0a', hair: '#0a0a0a' },
    accessories: ['roundHat', 'longBeard'],
  },
]

export function levelFor(level) {
  // 1-indexed level → loops with prestige
  const idx = (level - 1) % LEVELS.length
  return LEVELS[idx]
}

export function totalLevels() {
  return LEVELS.length
}
